# Generated by Django 5.2.8 on 2025-12-05 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Sin Nombre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(default='Sin Resumen', max_length=400)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('es_destacado', models.BooleanField(default=False)),
                ('link_spotifylist', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen_post', models.ImageField(blank=True, null=True, upload_to='imagenes_post/')),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogInfo.autor')),
                ('categoria_post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BlogInfo.categoria')),
                ('categorias', models.ManyToManyField(blank=True, related_name='posts', to='BlogInfo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_comentario', models.TextField()),
                ('fecha_comentario', models.DateField(default=django.utils.timezone.now)),
                ('autor_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='BlogInfo.comentario')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='BlogInfo.post')),
            ],
        ),
    ]
