"""
Django settings for proyectoInfo project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Indica cual es la ruta base para llegar al proyecto ---
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))    Configuracion original

BASE_DIR = Path(__file__).resolve().parent.parent       # Nueva configuracion para que funcione el Widget

MEDIA_URL = '/media/'                           # Agregado para imagenes de post
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')    # Agregado para imagenes de post

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%_=ld(2z90fz$-*7=&^dcma6v$6=5*ru_e0#@3*u93tbdj#6%m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['gmercado.pythonanywhere.com',"127.0.0.1"]

# Application definition

#Aplicaciones que ya vienen instaladas o definidas --- 
INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",  # required'django.contrib.admin',
    "ckeditor",              # Esto lo agregue
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',  # Para que funcione la mensajeria interna de Django
    'django.contrib.staticfiles',
    'BlogInfo',
    'django.contrib.humanize',
    'blog_auth',            # Agrego la aplicacion blog_auth OK!


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Aca tenemos que definir donde esta el archivo url.py ---
ROOT_URLCONF = 'proyectoInfo.urls'

TEMPLATES_DIR = os.path.join(BASE_DIR, 'template')
TEMPLATES_BLOG = os.path.join(BASE_DIR, 'template/blog')
TEMPLATES_AUTH = os.path.join(BASE_DIR, 'template/auth') # Carpeta de Logueo y Registro OK!


# Definmos donde están todos los templates ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR,TEMPLATES_BLOG,TEMPLATES_AUTH],  # Agrego la carpeta de Template de Registro y de logueo OK!
        # Notar: En la clase DIRS no tien corchetes pero si se los saco da error
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Le dice cual es la url del archivo wsgi.py

WSGI_APPLICATION = 'proyectoInfo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Para mysql
#DATABASES = {
#'default': {
#   'ENGINE': 'django.db.backends.mysql', # Specify the MySQL engine
#   'NAME': 'your_database_name', # Name of your MySQL database
#   'USER': 'your_mysql_user', # Username for your MySQL database
#   'PASSWORD': 'your_mysql_password', # Password for your MySQL user
#   'HOST': 'localhost', # Hostname of your MySQL server (e.g., 'localhost' or an IP address)
#   'PORT': '3306', # Port of your MySQL server (default is 3306)
#}
#}
#}
#}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = (os.path.join(BASE_DIR, "static")),            Configuracion original

# Lo siguiente es pra que ubique los css para el widget bendito! 
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_ROOT = BASE_DIR / "staticfiles"  # Para que funcione collectatic

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Lo que sigue es para que el Widget funcione con las etiquetas html y estilos css! 

CKEDITOR_CONFIGS = {
    'default': {
        # Con barra'Custom' muestra la barra avanzada!
        'toolbar': 'Custom', 
        
        'toolbar_Custom': [
            ['Source', '-', 'Maximize'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            
            # Botones de formatos: 'Format' y 'Styles'
            ['Format', 'Styles', 'Font', 'FontSize'], 
            
            '/', # <-- Separador para una nueva línea en la barra
            
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor', 'Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar'],
            
            '/', 
            
            ['TextColor', 'BGColor'],
            
        ],
        
        # Estilos definidos anteriormente (Ajusta los colores fijos)
        'stylesSet': [
            # Títulos
            {'name': 'Título 1', 'element': 'h1'},
            {'name': 'Título 2', 'element': 'h2'},
            
            # H3 Subtítulo (Replica estilos con colores fijos)
            {'name': 'Subtítulo con Barra (H3)', 
             'element': 'h3', 
             'styles': {
                 'font-size': '1.5rem',
                 'color': '#333333',
                 'border-left': '4px solid #FF0000', # Color para el borde
                 'padding-left': '1rem'
             }
            },
            
            # 4. PÁRRAFO NORMAL (REPLICANDO .post-detail__content p)
            {'name': 'Párrafo Principal', 
             'element': 'p', 
             'styles': {
                'font-size': '1rem',
                'color': '#333333', # Color fijo para --text-dark (ajusta si es necesario)
                'margin-bottom': '1.5rem',
                'line-height': '1.7'
     }
    },

            # Copete/Lead
            {'name': 'Introducción (Copete)', 
             'element': 'p', 
             'styles': {
                 'font-size': '1.125rem',
                 'font-weight': '500',
                 'border-left': '4px solid #007bff', # Color para el borde
                 'padding-left': '1rem'
             }
            },
        ],
        
        
        # 'contentsCss': ['/static/css/style_articulo.css'],
        
        'width': 'auto',
        'height': 400,
    }
}

